<?php
/**
 * This file merges in the custom Person schema for the user into the JSON-LD schema output
 * generated by All-In-One SEO plugin.
 */
namespace JSON_LD_Author_Plugin;

\add_filter( 'aioseo_schema_output', 'JSON_LD_Author_Plugin\aioseo_author_schema_output', 999, 1 );
function aioseo_author_schema_output($schema) {
  $count = find_all_in_multidimensional_array($schema, function($key, $value) {
    // if ( $key === 'author' ) {
    //   return true;
    // }

    if ( is_array($value) && isset($value['@type']) && $value['@type'] === 'Person' ) {
      return true;
    }
    
    return false;
  }, $results);

  if ( $count === 0 ) {
    return $schema;
  }

  $id = get_user_id_from_person_id( $results[0]['@id'] );
  $person_schema = get_person_schema_for_user( $id );
  append_schema($results[0], $person_schema);
  return $schema;
}
