<?php
/**
 * This file merges in the custom Person schema for the user into the JSON-LD schema output
 * generated by the Yoast plugin.
 */
namespace JSON_LD_Author_Plugin;

\add_filter( 'wpseo_schema_person_data', 'JSON_LD_Author_Plugin\yoast_schema_change_person', 999, 2 );


function yoast_schema_change_person( $schema, $user_id ) {
  if ( ! $user_id ) {
    return $schema;
  }

  $person_schema = get_person_schema_for_user( $user_id );
  unset( $person_schema['@id'] );
  append_schema( $schema, $person_schema );
  return $schema;
}

