<?php
/**
 * This file merges in the custom Person schema for the user into the JSON-LD schema output
 * generated by the Yoast plugin.
 */
namespace JSON_LD_Author_Plugin;

use Yoast\WP\SEO\Helpers\Schema\ID_Helper;

// Author (Person) of an Article
\add_filter( 'wpseo_schema_person_data', 'JSON_LD_Author_Plugin\yoast_schema_change_person_data', 999, 2 );

function yoast_schema_change_person_data( $schema, $user_id ) {
  if ( ! $user_id ) {
    return $schema;
  }

  $person_schema = get_person_schema_for_user( $user_id );
  unset( $person_schema['@id'] );
  append_schema( $schema, $person_schema );
  return $schema;
}

// Person of a ProfilePage
\add_filter( 'wpseo_schema_webpage', 'JSON_LD_Author_Plugin\yoast_schema_webpage', 999, 2);

function yoast_schema_webpage( $schema, $context ) {
  if ( $schema['@type'] !== 'ProfilePage' ) {
    return $schema;
  }

  $user_id = $context->indexable->id;
  $person_schema = get_person_schema_for_user( $context->indexable->id );

  $person_schema['@type'] = 'Person';
  $id_helper = new ID_Helper();
  $person_schema['@id'] = $id_helper->get_user_schema_id( $user_id, $context );

  $schema['mainEntity'] = $person_schema;

  return $schema;
}